apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      volumes:
        - name: resources
          emptyDir: { }
        - name: bootstrap
          configMap:
            name: {{ include "configmap.name" . }}
      initContainers:
        - name: transfer-resources
          image: {{ printf "%s/%s/%s:%s" .Values.init_image.app.registry .Values.init_image.app.repository .Values.init_image.app.image .Values.init_image.app.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: resources
              mountPath: {{ .Values.deployment.resourcesMountPath }}
          command: [ "/bin/sh", "-c" ]
          args:
            - >
              set -ex;
              cp -r /coze-loop/resources/* {{ .Values.deployment.resourcesMountPath | quote }};
      containers:
        - name: {{ include "application.name" . }}
          image: {{ include "image.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: resources
              mountPath: {{ .Values.deployment.resourcesMountPath }}
              readOnly: true
            - name: bootstrap
              mountPath: {{ include "bootstrap.path" . }}
              readOnly: true
          env:
            - name: COZE_LOOP_OSS_PROTOCOL
              value: {{ .Values.proxy.oss.protocol }}
            - name: COZE_LOOP_OSS_DOMAIN
              value: {{ .Values.proxy.oss.domain }}
            - name: COZE_LOOP_OSS_PORT
              value: {{ .Values.proxy.oss.port | quote }}
            - name: COZE_LOOP_OSS_BUCKET
              value: {{ .Values.proxy.oss.bucket }}
          command: [ "/bin/sh" ]
          args: [ {{ include "entrypoint.path" . | quote }} ]
          livenessProbe:
            exec:
              command: [ "/bin/sh", {{ include "healthcheck.path" . | quote }} ]
            initialDelaySeconds: {{ .Values.liveness.startSeconds }}
            periodSeconds: {{ .Values.liveness.intervalSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.liveness.shutdownFailureTimes }}