// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/apis/observabilityopenapiservice"
)

var observabilityOpenAPIClient observabilityopenapiservice.Client

// IngestTraces .
// @router /v1/loop/traces/ingest [POST]
func IngestTraces(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.IngestTraces)
}
