ingress:
  host: open.coze-loop.minikube
  type: nginx
  className: nginx

custom: &custom
  image:
    registry: "docker.io"
  redis:
    disabled: false
    domain: "***"
    port: "***"
    password: "***"
  mysql:
    disabled: false
    domain: "***"
    port: "***"
    user: "***"
    password: "***"
    database: "***"
  clickhouse:
    disabled: false
    domain: "***"
    port: "***"
    user: "***"
    password: "***"
    database: "***"
  oss:
    disabled: false
    protocol: "***"
    domain: "***"
    port: "***"
    region: "***"
    user: "***"
    password: "***"
    bucket: "***"
  rmq:
    disabled: false
    namesrv:
      domain: "***"
      port: "***"
      user: "***"
      password: "***"

coze-loop-app:
  custom: *custom
coze-loop-nginx:
  custom: *custom
coze-loop-redis:
  custom: *custom
coze-loop-mysql:
  custom: *custom
coze-loop-clickhouse:
  custom: *custom
coze-loop-minio:
  custom: *custom
coze-loop-rmq-namesrv:
  custom: *custom
coze-loop-rmq-broker:
  custom: *custom