ingress:
  host: open.coze-loop.minikube
  type: vke
  className: cozeloop-alb
  instanceName: cozeloop-alb

custom: &custom
  image:
    registry: "docker.io"
  mysql:
    disabled: false
    domain: "***"
    port: "***"
    user: "***"
    password: "***"
    database: "***"
  clickhouse:
    disabled: false
    domain: "***"
    port: "***"
    user: "***"
    password: "***"
    database: "***"

coze-loop-app:
  custom: *custom
coze-loop-nginx:
  custom: *custom
coze-loop-redis:
  custom: *custom
coze-loop-mysql:
  custom: *custom
coze-loop-clickhouse:
  custom: *custom
coze-loop-minio:
  custom: *custom
coze-loop-rmq-namesrv:
  custom: *custom
coze-loop-rmq-broker:
  custom: *custom