service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

image:
  registry: "docker.io"
  repository: "minio"
  image: "minio"
  tag: "RELEASE.2025-06-13T11-33-47Z"
  pullPolicy: IfNotPresent
  pullSecrets: "coze-loop-image-secret"

deployment:
  replicaCount: 1
  dataMountPath: "/minio_data"
  configMountPath: "/root/.minio"
  terminationGracePeriodSeconds: 10

liveness:
  startSeconds: 5
  intervalSeconds: 5
  timeoutSeconds: 3
  shutdownFailureTimes: 5

auth:
  user: "root"
  password: "coze-loop"

bucket:
  name: "coze-loop"

# customization
custom:
  image:
    registry:
    pullSecrets: