service:
  type: ClusterIP
  port: 8888
  targetPort: 8888

image:
  registry: "compose-cn-beijing.cr.volces.com"
  repository: "coze"
  image: "coze-loop"
  tag: "latest"
  pullPolicy: Always
  pullSecrets: "coze-loop-image-secret"

init_image:
  redis:
    registry: "compose-cn-beijing.cr.volces.com"
    repository: "library"
    image: "redis"
    tag: "latest"
  mysql:
    registry: "compose-cn-beijing.cr.volces.com"
    repository: "library"
    image: "mysql"
    tag: "latest"
  clickhouse:
    registry: "compose-cn-beijing.cr.volces.com"
    repository: "clickhouse"
    image: "clickhouse-server"
    tag: "latest"
  minio:
    registry: "compose-cn-beijing.cr.volces.com"
    repository: "minio"
    image: "minio"
    tag: "latest"
  rmq:
    registry: "compose-cn-beijing.cr.volces.com"
    repository: "rmq"
    image: "rocketmq"
    tag: "latest"

deployment:
  replicaCount: 1
  terminationGracePeriodSeconds: 5

liveness:
  startSeconds: 10
  intervalSeconds: 10
  timeoutSeconds: 30
  shutdownFailureTimes: 30

env:
  redis:
    domain: "coze-loop-redis"
    port: "6379"
    password: "coze-loop"
  mysql:
    domain: "coze-loop-mysql"
    port: "3306"
    user: "root"
    password: "coze-loop"
    database: "coze-loop"
  clickhouse:
    domain: "coze-loop-clickhouse"
    port: "9000"
    user: "default"
    password: "coze-loop"
    database: "coze-loop"
  oss:
    protocol: "http"
    domain: "coze-loop-minio"
    port: "9000"
    region: "us-east-1"
    user: "root"
    password: "coze-loop"
    bucket: "coze-loop"
  rmq:
    namesrv:
      domain: "coze-loop-rmq-namesrv"
      port: "9876"
      user: ""
      password: ""