service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  debugPort: 40000
  targetDebugPort: 40000
  hertzPort: 8888
  targetHertzPort: 8888

image:
  # meta
  registry: "cozeloop-cn-beijing.cr.volces.com"
  repository: "cozeloop"
  image: "server"
  tag: "1.0.0"
  # action
  pullPolicy: Always
  #  pullPolicy: IfNotPresent
  pullSecrets: "cozeloop-image-secret"

deployment:
  # meta
  replicaCount: 1
  # performance
  terminationGracePeriodSeconds: 5

liveness:
  startSeconds: 10
  intervalSeconds: 10
  timeoutSeconds: 30
  shutdownFailureTimes: 30

env:
  RUN_MODE: "release"
  COZELOOP_APP_HERTZ_PORT_POD: "8888"
  # redis
  COZELOOP_REDIS_ADDR_ACCESS: "cozeloop-redis:6379"
  COZELOOP_REDIS_PASSWORD: "cozeloop-redis-password"
  COZELOOP_REDIS_ADDR_ACCESS_CUSTOMIZED:
  COZELOOP_REDIS_PASSWORD_CUSTOMIZED:
  # mysql
  COZELOOP_MYSQL_HOST_ACCESS: "cozeloop-mysql"
  COZELOOP_MYSQL_PORT_ACCESS: "3306"
  COZELOOP_MYSQL_DATABASE: "cozeloop-mysql-database"
  COZELOOP_MYSQL_USER: "root"
  COZELOOP_MYSQL_PASSWORD: "cozeloop-mysql-password"
  COZELOOP_MYSQL_HOST_ACCESS_CUSTOMIZED:
  COZELOOP_MYSQL_PORT_ACCESS_CUSTOMIZED:
  COZELOOP_MYSQL_DATABASE_CUSTOMIZED:
  COZELOOP_MYSQL_USER_CUSTOMIZED:
  COZELOOP_MYSQL_PASSWORD_CUSTOMIZED:
  # clickhouse
  COZELOOP_CLICKHOUSE_ADDR_ACCESS: "cozeloop-clickhouse:9008"
  COZELOOP_CLICKHOUSE_DATABASE: "cozeloop-clickhouse-database"
  COZELOOP_CLICKHOUSE_USER: "default"
  COZELOOP_CLICKHOUSE_PASSWORD: "cozeloop-clickhouse-password"
  COZELOOP_CLICKHOUSE_ADDR_ACCESS_CUSTOMIZED:
  COZELOOP_CLICKHOUSE_DATABASE_CUSTOMIZED:
  COZELOOP_CLICKHOUSE_USER_CUSTOMIZED:
  COZELOOP_CLICKHOUSE_PASSWORD_CUSTOMIZED:
  # oss
  COZELOOP_OSS_REGION: "us-east-1"
  COZELOOP_OSS_ADDR_ACCESS: "cozeloop-minio:19000"
  COZELOOP_OSS_ENDPOINT_ACCESS: "http://cozeloop-minio:19000"
  COZELOOP_OSS_BUCKET: "cozeloop-minio-bucket"
  COZELOOP_OSS_USER: "root"
  COZELOOP_OSS_PASSWORD: "cozeloop-minio-password"
  COZELOOP_OSS_REGION_CUSTOMIZED:
  COZELOOP_OSS_ADDR_ACCESS_CUSTOMIZED:
  COZELOOP_OSS_ENDPOINT_ACCESS_CUSTOMIZED:
  COZELOOP_OSS_BUCKET_CUSTOMIZED:
  COZELOOP_OSS_USER_CUSTOMIZED:
  COZELOOP_OSS_PASSWORD_CUSTOMIZED:
  # rmqnamesrv
  COZELOOP_RMQNAMESRV_ADDR_ACCESS: "cozeloop-rmqnamesrv:9876"
  COZELOOP_RMQNAMESRV_USER:
  COZELOOP_RMQNAMESRV_PASSWORD:
  COZELOOP_RMQNAMESRV_ADDR_ACCESS_CUSTOMIZED:
  COZELOOP_RMQNAMESRV_USER_CUSTOMIZED:
  COZELOOP_RMQNAMESRV_PASSWORD_CUSTOMIZED: