apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.name" . }}
  labels:
    app: {{ include "application.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.tcpPort }}
      targetPort: {{ .Values.service.targetTcpPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.targetHttpPort }}
  selector:
    app: {{ include "application.name" . }}