apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configmap-etc.name" . }}
data:
  client.cfg: |-
{{ .Files.Get "etc/client.cfg" | indent 4 }}
{{- range $path, $file := .Files.Glob "etc/init-sql/*.sql" }}
  "{{ base $path }}": |-
{{ $file | toString | indent 4 }}
{{- end }}