# .air.toml
# 配置air监控和构建

root = "/cozeloop"
tmp_dir = "tmp"

[build]
cmd = "sh /cozeloop-server/build.backend.sh"
bin = "main"
full_bin = "/cozeloop-bin/backend/dev/main"
include_ext = ["go", "mod", "sum", "tpl", "tmpl"]
exclude_dir = ["tmp", "vendor", ".git", "script", "frontend", "conf", "release", "idl", "docs"]
delay = 1000

[log]
level = "debug"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"