apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      volumes:
        - name: bootstrap
          configMap:
            name: {{ include "configmap.name" . }}
      containers:
        - name: {{ include "application.name" . }}
          image: {{ include "image.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: bootstrap
              mountPath: {{ include "bootstrap.path" . }}
              readOnly: true
          env:
            # redis
            - name: COZE_LOOP_REDIS_DOMAIN
              value: {{ .Values.env.redis.domain }}
            - name: COZE_LOOP_REDIS_PORT
              value: {{ .Values.env.redis.port | quote }}
            - name: COZE_LOOP_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: redis-password
            # mysql
            - name: COZE_LOOP_MYSQL_DOMAIN
              value: {{ .Values.env.mysql.domain }}
            - name: COZE_LOOP_MYSQL_PORT
              value: {{ .Values.env.mysql.port | quote }}
            - name: COZE_LOOP_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: mysql-user
            - name: COZE_LOOP_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: mysql-password
            - name: COZE_LOOP_MYSQL_DATABASE
              value: {{ .Values.env.mysql.database }}
            # clickhouse
            - name: COZE_LOOP_CLICKHOUSE_DOMAIN
              value: {{ .Values.env.clickhouse.domain }}
            - name: COZE_LOOP_CLICKHOUSE_PORT
              value: {{ .Values.env.clickhouse.port | quote }}
            - name: COZE_LOOP_CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: clickhouse-user
            - name: COZE_LOOP_CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: clickhouse-password
            - name: COZE_LOOP_CLICKHOUSE_DATABASE
              value: {{ .Values.env.clickhouse.database }}
            # oss
            - name: COZE_LOOP_OSS_PROTOCOL
              value: {{ .Values.env.oss.protocol }}
            - name: COZE_LOOP_OSS_DOMAIN
              value: {{ .Values.env.oss.domain }}
            - name: COZE_LOOP_OSS_PORT
              value: {{ .Values.env.oss.port | quote }}
            - name: COZE_LOOP_OSS_REGION
              value: {{ .Values.env.oss.region }}
            - name: COZE_LOOP_OSS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: oss-user
            - name: COZE_LOOP_OSS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: oss-password
            - name: COZE_LOOP_OSS_BUCKET
              value: {{ .Values.env.oss.bucket }}
            # rmq
            - name: COZE_LOOP_RMQ_NAMESRV_DOMAIN
              value: {{ .Values.env.rmq.namesrv.domain }}
            - name: COZE_LOOP_RMQ_NAMESRV_PORT
              value: {{ .Values.env.rmq.namesrv.port | quote }}
            - name: COZE_LOOP_RMQ_NAMESRV_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: rmq-namesrv-user
            - name: COZE_LOOP_RMQ_NAMESRV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: rmq-namesrv-password
          command: [ "/bin/sh" ]
          args: [ {{ include "entrypoint.path" . | quote }} ]
          livenessProbe:
            exec:
              command: [ "/bin/sh", {{ include "healthcheck.path" . | quote }} ]
            initialDelaySeconds: {{ .Values.liveness.startSeconds }}
            periodSeconds: {{ .Values.liveness.intervalSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.liveness.shutdownFailureTimes }}