custom: &custom
  image:
    registry: "compose-cn-beijing.cr.volces.com"
    pullSecrets: "coze-loop-image-secret"
  redis:
    disabled: true
  mysql:
    disabled: true
  clickhouse:
    disabled: true
  oss:
    disabled: true
  rmq:
    disabled: true

coze-loop-app:
  custom: *custom
coze-loop-nginx:
  custom: *custom
coze-loop-redis:
  custom: *custom
coze-loop-mysql:
  custom: *custom
coze-loop-clickhouse:
  custom: *custom
coze-loop-minio:
  custom: *custom
coze-loop-rmq-namesrv:
  custom: *custom
coze-loop-rmq-broker:
  custom: *custom